//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eocean.Parking.Financeiro.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despesa
    {
        public int IdDespesa { get; set; }
        public string Descricao { get; set; }
        public decimal ValorDespesa { get; set; }
        public Nullable<System.DateTime> DtPagamento { get; set; }
        public Nullable<System.DateTime> DtVencimento { get; set; }
        public bool Pago { get; set; }
        public bool PossuiParcelas { get; set; }
        public Nullable<int> QtParcelas { get; set; }
        public Nullable<int> IdDespesaCategoria { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string CodDespesa { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
    
        public virtual DespesaCategoria DespesaCategoria { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
