//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eocean.Parking.Financeiro.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Despesa = new HashSet<Despesa>();
        }
    
        public int IdFuncionario { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> DtAdmissao { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public int IdPessoa { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despesa> Despesa { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
