//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eocean.Parking.Financeiro.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensalista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensalista()
        {
            this.Receita = new HashSet<Receita>();
        }
    
        public int IdMensalista { get; set; }
        public int IdPessoa { get; set; }
        public string PlacaVeiculo { get; set; }
        public string MarcaModeloVeiculo { get; set; }
        public string Cor { get; set; }
        public string TipoVeiculo { get; set; }
        public decimal ValorMensalidade { get; set; }
        public Nullable<System.DateTime> DtInicio { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DtCadastro { get; set; }
        public Nullable<System.DateTime> DtAlteracao { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receita> Receita { get; set; }
    }
}
